# -*- coding: utf-8 -*-

from odoo import api, models


class MrpProduction(models.Model):
    _inherit = 'mrp.production'

    def _prepare_stock_lot_values(self):
        """Override to NOT provide name - let auto-generation handle it
        
        This ensures that when MO is confirmed and lot_producing_id is created,
        the lot name will be auto-generated by our stock.lot.create() method
        based on product category (SFG or FG) and financial year.
        
        Note: This override takes precedence over product_secondary_uom module
        to ensure our auto-generation format is used.
        """
        self.ensure_one()
        # Don't set name - let stock.lot.create() auto-generate it
        # based on product category and financial year
        # Include company_id as it might be required by stock.lot model
        vals = {
            'product_id': self.product_id.id,
            # name will be auto-generated in stock.lot.create()
        }
        # Add company_id if available (for compatibility with stock.lot requirements)
        if hasattr(self, 'company_id') and self.company_id:
            vals['company_id'] = self.company_id.id
        return vals

    def action_confirm(self):
        """Override to auto-generate lot_producing_id when MO is confirmed
        
        For Semi-Finished Goods (SFG) and Finished Goods (FG), automatically
        create and assign lot_producing_id with auto-generated lot/serial number.
        """
        res = super(MrpProduction, self).action_confirm()
        
        # Auto-generate lot for products with tracking (SFG or FG)
        for production in self:
            # Only for products with lot/serial tracking
            if production.product_id.tracking in ('lot', 'serial'):
                # Only if lot_producing_id is not already set
                if not production.lot_producing_id:
                    # Auto-generate lot - this will call _set_lot_producing()
                    # which creates stock.lot with auto-generated name based on category
                    try:
                        production._set_lot_producing()
                    except Exception:
                        # If lot creation fails, continue without it
                        # User can manually generate later
                        pass
        
        return res
